Migrating to spree 4.1
katapulk/spree-admin-insights pull request #1
Opened 2021-01-04 19:26 UTC by JDavid17

Not ready yet.

2021-01-05 18:46 UTC, efrenvalfonso requested changes

2021-01-05 18:46 UTC, efrenvalfonso commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
este codigo `wicked_pdf_image_tag image_path, class: 'logo'` tiene que estar en

def self.prepend(base)
.... base.wicked_pdf_image_tag image_path, class: 'logo'
end

ya que `wicked_pdf_image_tag` se ejecuta cuando se evalua la clase, no en la instancia.

2021-01-05 22:17 UTC, JDavid17 commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
Y como mantendria entonces al metodo pdf_logo?

2021-01-05 23:03 UTC, efrenvalfonso commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
no entiendo la pregunta. lo que estas haciendo ahi es evaluar las cosas del modulo cuando se hace el prepend en las clases que es incluido. cuando esto se hace `wicked_pdf_image_tag image_path, class: 'logo'` en la forma antigua forma del decorador es lo mismo que un `has_many` o cualquier otra funcion que se corra cuando se esta evaluando la clase. esto tienes que ejecutarlo con `base` ya que es lo mismo que haces con los `has_many`, los `include` o cualquier otra funcion que se ejecute con la creacion de la clase

2021-01-06 02:49 UTC, JDavid17 commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
A ver, probablemente sea un malentendido mio, pero segun veo en el codigo, no se pretende que funcione igual que un `has_many` que se ejecutaria cuando se evalua la clase, en el `base_helper_decorator` lo tienen definido dentro de un metodo `pdf_logo` y este metodo entonces lo usan en una vista `download.pdf.erb`. Si lo pongo como dice, entonces simplemente cuando `base` le haga `prepend` al decorador se evaluara el `wicked_pdf_image_tag` y ya, como se resolveria eso despues en la vista entonces? No se si me explico.

2021-01-06 04:25 UTC, JDavid17 commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
En cualquier caso, manana voy a cerrar este draft, al final termine trabajando sobre otra rama asi que subire el PR bien con esa. Ya logre adaptar e inyectar bien el contenido del insights al panel de administracion, y adaptarlo al estilo que tienen la app. Los issues que tengo se los pondre en el Readme bien detallados, para que le sea mas rapido.

2021-01-06 13:49 UTC, JDavid17 commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
Me avisa cuando lea esto para cerrarlo, ya ire subiendo el otro

2021-01-06 13:55 UTC, efrenvalfonso commented on app/helpers/spree/admin/base_helper_decorator.rb
>      wicked_pdf_image_tag image_path, class: 'logo'
Perfecto papo. Mejor así. Si ya lo tienes resuelto nada más que discutir

2021-01-06 15:00 UTC, closed without merging